cloud:
  aws:
    credentials:
      access-key: AKIAXO526BU6TDOEJW7Z
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: angelstorages

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://porcinosdb.cnyzaqfgqvkn.us-east-1.rds.amazonaws.com:3306/porcinosaws
    username: root
    password: secretsecret
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      max_allowed_packet: 2000

server:
  port: 8080

