cloud:
  aws:
    credentials:
      access-key: {ACCESS_KEY}
      secret-key: {SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: angelstorages

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://porcinosdb.cvdmtpiixomp.us-east-2.rds.amazonaws.com:3306/porcinosaws
    username: root
    password: secretsecret
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      max_allowed_packet: 2000

server:
  port: 8080

